version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=key
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres:5432/etl_db
      - AIRFLOW__WEBSERVER__WORKERS=1
    volumes:
      - C:/Users/UserPC/Documents/elt3/airflow/dags:/opt/airflow/dags
      - C:/Users/UserPC/Documents/elt3/airflow/logs:/opt/airflow/logs
      - C:/Users/UserPC/Documents/elt3/airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=key
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres:5432/etl_db
    volumes:
      - C:/Users/UserPC/Documents/elt3/airflow/dags:/opt/airflow/dags
      - C:/Users/UserPC/Documents/elt3/airflow/logs:/opt/airflow/logs
      - C:/Users/UserPC/Documents/elt3/airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - mongodb
      - airflow-webserver
    command: scheduler

volumes:
  mongo-data:
  postgres-data:
